services:
  db:
    image: postgres:16-alpine
    container_name: api-assinaturas-db
    environment:
      POSTGRES_DB: api_assinaturas
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api -d api_assinaturas"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: api-assinaturas-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8098:8098"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:

